name: Compile GMpro Final Rescue

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Deauther Core
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install All Libraries (Force Method)
        run: |
          LIB_PATH=$HOME/Arduino/libraries
          mkdir -p $LIB_PATH
          
          # 1. Install Library Standar
          arduino-cli lib install "SimpleCLI"
          arduino-cli lib install "ArduinoJson"@5.13.5
          
          # 2. Download Async Libraries (Tanpa Git Clone yang bermasalah)
          curl -L https://github.com/me-no-dev/ESPAsyncTCP/archive/refs/heads/master.zip -o tcp.zip
          unzip tcp.zip -d $LIB_PATH/ && mv $LIB_PATH/ESPAsyncTCP-master $LIB_PATH/ESPAsyncTCP
          
          curl -L https://github.com/me-no-dev/ESPAsyncWebServer/archive/refs/heads/master.zip -o server.zip
          unzip server.zip -d $LIB_PATH/ && mv $LIB_PATH/ESPAsyncWebServer-master $LIB_PATH/ESPAsyncWebServer

          # 3. DOWNLOAD SELURUH SDK LIBRARIES (Penting!)
          # Kita ambil semua file .h dan .cpp agar tipe data Attack & Scan dikenali
          curl -L https://github.com/SpacehuhnTech/ESP8266Deauther/archive/refs/heads/master.zip -o deauther.zip
          unzip deauther.zip "ESP8266Deauther-master/esp8266_deauther/src/libraries/*" -d temp_sdk
          cp -r temp_sdk/ESP8266Deauther-master/esp8266_deauther/src/libraries/* $LIB_PATH/
          
          # Bersihkan file sampah
          rm *.zip && rm -rf temp_sdk

      - name: Compile GMpro Firmware
        run: |
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          --libraries $HOME/Arduino/libraries \
          ./GMpro1.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro-Deauther-Binary
          path: ./build/*.bin
