name: Compile GMpro Deauther Fixed Library

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Dependencies & Async Libraries
        run: |
          mkdir -p $HOME/Arduino/libraries
          arduino-cli lib install "SimpleCLI"
          # Clone Async Libraries
          git clone https://github.com/me-no-dev/ESPAsyncTCP.git $HOME/Arduino/libraries/ESPAsyncTCP
          git clone https://github.com/me-no-dev/ESPAsyncWebServer.git $HOME/Arduino/libraries/ESPAsyncWebServer
          # Install ArduinoJson v5 (Wajib versi 5 untuk Deauther)
          arduino-cli lib install "ArduinoJson"@5.13.5

      - name: Compile GMpro Firmware
        run: |
          # Mendapatkan path internal core deauther agar Attack.h terbaca
          CORE_LIB_PATH=$HOME/.arduino15/packages/deauther/hardware/esp8266/2.7.5/libraries
          
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          --libraries $HOME/Arduino/libraries \
          --libraries $CORE_LIB_PATH/Attack \
          --libraries $CORE_LIB_PATH/Scan \
          --libraries $CORE_LIB_PATH/A_Config \
          ./GMpro1.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro-Deauther-Binary
          path: ./build/*.bin
